import { Inter } from 'next/font/google'
import { Raleway } from 'next/font/google'
import '@/styles/globals.css'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import { AuthContextProvider } from '@/contexts/AuthContext'
import ModalProvider from '@/components/layout/ModalWrapper/components/ModalProvider'

const inter = Inter({ subsets: ['latin'] })
const raleway = Raleway({ subsets: ['latin'] })

export const metadata = {
  title: 'Cure Sharp',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthContextProvider>
        <ModalProvider>
          <body className={(inter.className, raleway.className)}>
            <ToastContainer />
            {children}
          </body>
        </ModalProvider>
      </AuthContextProvider>
    </html>
  )
}
